---
hosts: localhost
gather_facts: no

vars:
  service_account_file: /home/my_account.json
  project: my-project
  auth_kind: serviceaccount
  scopes:
    - https://www.googleapis.com/auth/compute

tasks:
 - name: Create Network
   gcp_compute_network:
     name: 'network-instance'
     project: "{{ gcp_project }}"
     auth_kind: "{{ gcp_cred_kind }}"
     service_account_file: "{{ gcp_cred_file }}"
     scopes:
       - https://www.googleapis.com/auth/compute
     state: present
 - name: Create SubNetwork
   gcp_compute_address:
       state: present
       name: 'test-address1'
       region: 'europe-west1'
       project: "{{ project }}"
       auth_kind: "{{ auth_kind }}"
       service_account_file: "{{ service_account_file }}"
       scopes: "{{ scopes }}"
 - name: Create Firewall
   gcp_compute_address:
       state: present
       name: 'test-address1'
       region: 'europe-west1'
       project: "{{ project }}"
       auth_kind: "{{ auth_kind }}"
       service_account_file: "{{ service_account_file }}"
       scopes: "{{ scopes }}"
 - name: Create Public IP
   gcp_compute_address:
       state: present
       name: 'test-address1'
       region: 'europe-west1'
       project: "{{ project }}"
       auth_kind: "{{ auth_kind }}"
       service_account_file: "{{ service_account_file }}"
       scopes: "{{ scopes }}"
 - name: Create Controllers
   gcp_compute_instance:
     state: present
     name: test-vm
     machine_type: n1-standard-1
     disks:
       - auto_delete: true
         boot: true
         source: "{{ disk }}"
     network_interfaces:
       - network: "{{ network }}"
         access_configs:
           - name: 'External NAT'
             nat_ip: "{{ address }}"
             type: 'ONE_TO_ONE_NAT'
     zone: "{{ zone }}"
     project: "{{ gcp_project }}"
     auth_kind: "{{ gcp_cred_kind }}"
     service_account_file: "{{ gcp_cred_file }}"
     scopes:
       - https://www.googleapis.com/auth/compute
 - name: Create Workers
   gcp_compute_instance:
     state: present
     name: test-vm
     machine_type: n1-standard-1
     disks:
       - auto_delete: true
         boot: true
         source: "{{ disk }}"
     network_interfaces:
       - network: "{{ network }}"
         access_configs:
           - name: 'External NAT'
             nat_ip: "{{ address }}"
             type: 'ONE_TO_ONE_NAT'
     zone: "{{ zone }}"
     project: "{{ gcp_project }}"
     auth_kind: "{{ gcp_cred_kind }}"
     service_account_file: "{{ gcp_cred_file }}"
     scopes:
       - https://www.googleapis.com/auth/compute
