# Install app into docker
- name: Image to docker
  hosts: docker
  become: true

  tasks:
    - debug: msg="This is in {{ env }} environment"

    # Pull image specified by variable default_image from the Docker Hub
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
