version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
            - post_db
            - comment_db

  ui:
    image: ${USERNAME}/ui:${UI_VER}
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    ports:
      - ${UI_PORT_FRONT}:${UI_PORT_BACK}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${POST_VER}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - front_net
      - back_net

  comment:
    image: ${USERNAME}/comment:${COMMENT_VER}
    environment:
      - COMMENT_DATABASE_HOST=comment_db
      - COMMENT_DATABASE=comments
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    networks:
      - front_net
      - back_net


volumes:
  post_db:

networks:
  front_net:
  back_net:
