groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'

    - alert: HighHttpRequestDuration
      expr: http_request_duration_microseconds > 100000
      for: 15m
      labels:
        severity: page
      annotations:
        summary: High http request duration

    - alert: CpuUserLoad
      expr: cpu_usage_user > 80
      for: 5m
      labels:
        severity: page
      annotations:
        summary: High Cpu User Load
